[package]
name = "mmxxiv_day16"
version = "0.1.0"
edition = "2021"

[lints.clippy]
pedantic = "deny"

[dependencies]
ahash = "0.8.11"
anyhow = "1.0.95"
test-case = "3.3.1"
astar = { workspace = true }
indoc = "2.0.7"
